### ISSUE TITLE
Content types imprort in Contentful

### ISSUE THREAD

**Issue by 2betafactor** [juhi-trivedi/cape#8]
Hi @juhitrivedi,

I am not sure how to imprort the content types in Contentful. Can you please share a json file?

thanks
Nik

**Comment by juhi-trivedi** [comment]
Hi @2betafactor ,

First of all, Thank you for using cape. You can find the json for both blog & person modal here:
[json.txt](https://github.com/juhitrivedi/cape/files/4479231/json.txt)

Let me know if you have any further query.

Thank you.
